cabal-version:       2.2

name:                password-manager
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/SebasCH04/password-manager
license:             BSD-3-Clause
license-file:        LICENSE
author:              Sebastián Calvo Hernández
maintainer:          sebcalvo@estudiantec.cr
copyright:           2025 Sebastián Calvo Hernández
category:            Web
build-type:          Simple
extra-source-files:  README.md
                     CHANGELOG.md

executable password-manager
  hs-source-dirs:      src
  main-is:             Main.hs
  default-language:    Haskell2010
  build-depends:
    base >=4.18 && <5,
    bytestring,
    cryptonite,
    cereal,
    directory,
    filepath,
    memory,
    optparse-applicative

  other-modules:
    Core.Types,
    Core.Crypto,
    Core.Storage,
    Core.PinAuth

  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints
